### ISSUE TITLE
Dogfood session 2019.11.04: Feedback and general remarks

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/cli#29] opened 2019-11-04 09:55 UTC
# Dogfood session November 4th, 2019

Hypergraph `v0.2.7`
Node `v10.16.0`
OS `Linux Mint`

## General non-interactive mode comments

+ I cannot autocomplete the hypergraph cli non-interactive commands? Might help in ease of use. E.g., when I have typed `hypergraph ` I tab to get the actions list.
+ Along that line, maybe having autocomplete for the `env` turned on for the actions that require a hash might help? I'm just brainfarting here
+ In non-interactive mode I get a prompt for omitted description, which may be left empty? It makes sense from our design philosophy, but maybe in the second and third lines of the next code block, it might not prompt for user-interaction? This would help simulate pseudo-usage in [`libscie/the-matrix`](https://github.com/libscie/the-matrix) later on as well.

```bash
hypergraph create profile -y -n Fartgerink
hypergraph create profile -y -n Fartgerink -d
hypergraph create profile -y -n Fartgerink -d ''
```

+ `hypergraph list` sounds like a valid option as well, 

## Create module

+ Maybe change `License: <url>` to `License (y/n): <url>`? I can hardly see the yes/no text so let's make sure they know what the prompt responses are?
+ `subtype` should default to empty I'd propose (this is already fixed i think https://github.com/p2pcommons/sdk-js/issues/22) --> really looking forward to having the subtype functionality with wikidata identifiers in as well :) https://github.com/hypergraph-xyz/cli/issues/20

## Update module metadata

+ For `type: content` if I update the `main` property the CLI doesn't complete (i.e., it gets stuck in wait and I don't get my bash session back)

## Pruning the functionality

+ I'd like to propose that we dumb down hypergraph. More functionality is more confusing, and I think we can set the scope for the CLI to: "The end-user can create modules, update metadata, and open the module on their local machine." From that, we could simplify the options in interactive mode for the end-user (non user facing functionality can still be available from cli, I'd think?). The `- <text> -` indicate suggested deletes and `+ <text> +` suggested additions.

```bash
? Pick an action › - Use arrow-keys. Return to submit.
   Create a module
   -Read metadata-
   -Update metadata-
   +Change module title/name+
   +Change module description+
   Open module folder
-❯  Print module path-
-   List writable modules-
```

Thanks @juliangruber for the good work :confetti_ball:

**Comment by juliangruber** [comment] 2019-11-04 12:05
> * I cannot autocomplete the hypergraph cli non-interactive commands? Might help in ease of use. E.g., when I have typed `hypergraph ` I tab to get the actions list.
> * Along that line, maybe having autocomplete for the `env` turned on for the actions that require a hash might help? I'm just brainfarting here

This isn't something we can include in the CLI, but can offer the users to install into their shell. It works by telling them to `source` a custom auto complete function, a line that needs to be added to their shell setup (eg `~/.profile` on Mac OS). The only CLI I have auto complete installed for personally is `git`, but also only for the branch names and not the commands (which would be the auto complete for the hashes in our case). Do you think we should offer the bit extra of UX? We can install this for the user on first run, asking them if we should add some lines to their shell setup.

> * In non-interactive mode I get a prompt for omitted description, which may be left empty? It makes sense from our design philosophy, but maybe in the second and third lines of the next code block, it might not prompt for user-interaction? This would help simulate pseudo-usage in [`libscie/the-matrix`](https://github.com/libscie/the-matrix) later on as well.

I agree, I've been wanting to fix this for a bit. This will be part of the next release!

> * Maybe change `License: <url>` to `License (y/n): <url>`? I can hardly see the yes/no text so let's make sure they know what the prompt responses are?

In the next release this y/n will be the same color as the main text 🍾 

<img width="570" alt="Screenshot 2019-11-04 at 12 03 55" src="https://user-images.githubusercontent.com/10247/68116464-33c05580-fefb-11e9-823d-e2c6d7678bff.png">

> * `subtype` should default to empty I'd propose (this is already fixed i think [p2pcommons/sdk-js#22](https://github.com/p2pcommons/sdk-js/issues/22)) --> really looking forward to having the subtype functionality with wikidata identifiers in as well :) #20

Will fix!

> * For `type: content` if I update the `main` property the CLI doesn't complete (i.e., it gets stuck in wait and I don't get my bash session back)

Ewps! Can you share exact steps to reproduce this? This works for me:

```bash
$ hypergraph create content -t=t -d=d -y
d54c821c43566cdcffd5ff09d03e3e9ef9c7c3b8c9a055041655ae6783c91e4e
$ echo beep > ~/.p2pcommons/d54c821c43566cdcffd5ff09d03e3e9ef9c7c3b8c9a055041655ae6783c91e4e/file.txt
$ hypergraph update
✔ Select module › t
✔ Title … t
✔ Description … d
✔ Main › file.txt
```

```bash
$ hypergraph update d54c821c43566cdcffd5ff09d03e3e9ef9c7c3b8c9a055041655ae6783c91e4e main file.txt
$
```

> ```shell
>    -Read metadata-
>    -Update metadata-
>    +Change module title/name+
>    +Change module description+
> ```

Would this mean removing the option to update `.main` and also in the future `.subtype`?

I think it's a good idea in general to make the default prompt more curated, this is for beginner users anyway and we don't need to list all the options. Iiuc you also propose to remove the `list` and `path` commands from this list, right?

**Comment by chartgerink** [comment] 2019-11-04 12:35
Aw great, thanks!

> Do you think we should offer the bit extra of UX?

I think it would be a good addition; if you agree we could include it.

> Ewps! Can you share exact steps to reproduce this? This works for me:

Oooh I tried again and I think it happened because the file I was adding was empty (I just did `touch file`). I see now that the path doesn't include the `./` part to indicate it is located in it's own folder. Do you think we'd need to force that in for clarity or is it redundant?

> Would this mean removing the option to update .main and also in the future .subtype?

Good that you mention this --- these should not be omitted because it's core functionality. The list and path commands are not very core to the user, so we can omit them from the prompt. If you feel strongly that the prompt and the actions the CLI has should be consistent, I'm open to that as well.

🎊

**Comment by juliangruber** [comment] 2019-11-04 12:50
> I think it would be a good addition; if you agree we could include it.

Ok! I'll look into this. What in your mind should be auto completed, the actions and the hashes? Or just the actions? I don't see hash completion useful, as if you have the beginning of a hash you also have the full hash available. We can try for the actions though?

> Oooh I tried again and I think it happened because the file I was adding was empty (I just did `touch file`). I see now that the path doesn't include the `./` part to indicate it is located in it's own folder. Do you think we'd need to force that in for clarity or is it redundant?

I also tried with an empty file and it always worked, and it worked with `./file` and `file`.

I don't think the extra `./` of a relative path hurts, node allows it as well.

> Good that you mention this --- these should not be omitted because it's core functionality.

Still not sure I get this. Are you suggesting we remove the `Update metadata` from the prompt, but add `Change module title/name` and `Change module description`, which would be special versions of the `update` command? And are you suggesting we leave the `update` command itself completely untouched?

This changes the prompt from "this is all you can do" to "here are some common actions you might want to be doing", is that what you're saying?

I have for now removed the `path` and `list` commands from the prompt.

**Comment by chartgerink** [comment] 2019-11-04 18:31
> We can try for the actions though?

Actions sounds good 👍 

> I also tried with an empty file and it always worked, and it worked with ./file and file.

Okay probably an issue on my end. I'll note to check it another time but no worries :)

> Still not sure I get this. 

Sorry for being imprecise and a bit confusing. I now notice I didn't think it through quite well.

>Are you suggesting we remove the Update metadata from the prompt, but add Change module title/name and Change module description, which would be special versions of the update command? And are you suggesting we leave the update command itself completely untouched?

> This changes the prompt from "this is all you can do" to "here are some common actions you might want to be doing", is that what you're saying?

Because of your questions I think it might not be the best option to do this; thanks :) It makes sense to have one action (i.e., `update`) that walks through all options instead of multiple more specific actions combined with options. It confounds the model we said we'd use. I should've thought this through a bit better..

**Comment by chartgerink** [comment] 2019-11-06 09:50
I think this issue can be closed if you don't need it anymore :)

**Comment by juliangruber** [comment] 2019-11-07 12:02
Awesome, closing :) The only open issue from this thread is https://github.com/hypergraph-xyz/cli/issues/35.

**Comment by juliangruber** [comment] 2019-11-07 12:03
> I should've thought this through a bit better..

That's what discussion is for :) Better also to leave some details open because sometimes things can take an even better turn when we talk!

**Closed by juliangruber** 2019-11-07 12:02 UTC
Labels: blocked
